### ISSUE TITLE
Integrate these facts with razorsedge/puppet-vmwaretools.

### ISSUE THREAD

**Issue by razorsedge** [wolfspyre/vmware_puppetfact#1]
I would love to include your facts in my [vmwaretools module](https://github.com/razorsedge/puppet-vmwaretools).  Thanks!

**Comment by wolfspyre** [comment]
Hi there!

I've refactored the facts, along with providing unit tests.

Want to take a look at it and see what you think now?

**Comment by razorsedge** [comment]
@wolfspyre 
1. I am not sure that a module that only contains a fact would need a class defined.  I imagine that the Puppet module docs say so, but it just seems weird to have an empty class.
2. Should there really be a fact named vmware on a non-vmware host?
3. In  lib/facter/vmware.rb you do Facter::Util::Resolution.exec('which dmidecode') and then assume that dmidecode is in a certain place with Facter::Util::Resolution.exec('/usr/sbin/dmidecode -t bios'). 

```
[root@localhost ~]# facter operatingsystem operatingsystemrelease
operatingsystem => Fedora
operatingsystemrelease => 18
[root@localhost ~]# which dmidecode
/sbin/dmidecode
```

Perhaps use the value of `hasdmi` something like `..exec(hasdmi '-t bios')`? (<- that is probably not the correct ruby code)
4. I like the approach of making this fact into a Forge module.  This way you can ship it as your own and my module (and other vmware tools modules) can depend on yours.

**Comment by wolfspyre** [comment]
Hi Mike,

I've refactored the mentioned bits.. I believe this to be usable now. Let
me know if anything else smells funny, and of not, I'll release to the
forge.

W

**Comment by razorsedge** [comment]
Wolf,

I see in .fixtures.yml you have a testing dependency on stdlib, but that isn't listed in Modulefile.  Is it really needed?  Also take a look at these commits on forks of vmware_puppetfact: ebdc68a18e0671b214ec10b11debc43f00ed591f and 7f4591c6d2b0a67eb29752902512a9fc07134561 and 04fc2532b53db0c67ff3d8fc7af2cba9797010ad.

**Comment by wolfspyre** [comment]
I like the 5.0u2 bit, and have merged. I've also pulled stdlib deps. I
blame old scaffolding.
:)

as to the vmware_tools_version fact, do you want this functionality?

Does it make more sense to you to have a unified fact, in addition to
having them separated? it seems to me that this logic could pretty clearly
be handled in the vmware_tools module in puppetcode, making the fact
creation somewhat superfluous, and makes the logic of what's going on a
little more apparent to the consumer of the tools module.

Thoughts?

**Comment by razorsedge** [comment]
@quiffman seems to indicate in 04fc2532b53db0c67ff3d8fc7af2cba9797010ad that Puppet 3 and Heira will see that the fact $::vmwaretools_tools_version exists and automagically pass that as a class parameter to my [puppet-vmwaretools](https://github.com/razorsedge/puppet-vmwaretools) module.  I think that is slick.  I am not sure, though, if that meta-fact should go in your module or possibly in mine.

**Comment by quiffman** [comment]
It does indeed, "Just Work"(TM).
We have PE 2.8 (so puppet 2.7) and all this needed to work was to sync this fact and include [puppet-vmwaretools](https://github.com/razorsedge/puppet-vmwaretools) on our agents. No hiera required!
I have used it with EL5 and EL6 on ESX versions 3.5, 4.1latest, 5.0u1 and 5.1. I _love_ having multiple providers!
Only minor hiccup was no ESX 3.5, EL6 repos...

From a third party perspective, I think this would make most sense if it was integrated in to [puppet-vmwaretools](https://github.com/razorsedge/puppet-vmwaretools).

Oh, and I'd just like to say @razorsedge, @wolfspyre: love your work, guys!

**Comment by wolfspyre** [comment]
Hi Richard,

Thanks for the kind words! To be certain I understand your viewpoint, are
you saying:
The vmware_tools_version fact be integrated into the puppet-vmwaretools
module?
The vmware_tools_version be merged into the puppet-vmwaretools module, and
that the fact module be placed on the forge as a dependency?

or something else that I'm entirely missing?

:)

**Comment by quiffman** [comment]
> The vmware_tools_version fact be integrated into the
> puppet-vmwaretools module?

Logically, I think this makes most sense.
The "include one puppet module and it just works" approach, is very appealing!

And of course, anyone who is interested in just the fact can still utilise it, by adding puppet-vmwaretools to their code base and just not 'include vmwaretools' anywhere.

FWIW: I don't use the forge directly - I prefer to import third party puppet modules as submodules of my main git repo.

Notice: This email and any attachments are confidential.
If received in error please destroy and immediately notify us.
Do not copy or disclose the contents.

**Comment by razorsedge** [comment]
@quiffman : Send me a PR with 04fc253 and I will include it with my next release.
@wolfspyre : This code looks good for the Forge.

**Comment by quiffman** [comment]
@razorsedge: 04fc253 is dependent on the other facts in vmware_puppetfact...
I think it would probably be better if @wolfspyre integrates all of vmware_puppetfact with puppet-vmwaretools and raises a PR from that.

Obviously I could do that myself, but I think @wolfspyre should get the opportunity first. Credit where credit is due.

Also, I'm about to go offline for a 12 hour flight...

**Comment by razorsedge** [comment]
> > The vmware_tools_version fact be integrated into the puppet-vmwaretools module?
> 
> Logically, I think this makes most sense. The "include one puppet module and it just works" approach, is very appealing!

@quiffman : I am confused.  It looked like you were agreeing with @wolfspyre to add your meta-fact to puppet-vmwaretools.  I intend to have the vmware_puppetfact module as a dependency of puppet-vmwaretools.  What am I missing?

**Comment by quiffman** [comment]
Sorry for the confusion.
I didn't realise that vmware_puppetfact was already planned as a dependency of puppet-vmwaretools.
I thought the whole vmware_puppetfact project would be integrated into puppet-vmwaretools.

Not fussed either way.

## 

Richard Guest - GeoNet Senior Software Engineer
GNS Science - Te Pu Ao
D +64-4-570-4854 :: M +64-27-415-1417 :: T +64-4-570-1444 :: F +64-4-570-4600
1 Fairway Drive, Avalon, PO Box 30-368, Lower Hutt, 5040, New Zealand.
http://www.gns.cri.nz/who/staff/2658.html

-----Mike Arnold notifications@github.com wrote: -----
To: wolfspyre/vmware_puppetfact vmware_puppetfact@noreply.github.com

**Comment by razorsedge** [comment]
@wolfspyre I noticed that you released your module to the Forge.  Are things stable?  If so, I will release an update to razorsedge/vmwaretools to depend on wolfspyre/vmware_puppetfact.

**Comment by wolfspyre** [comment]
I've been slammed this week. I'll submit a PR including the fact, and tests
into vmwaretools natively. when changes get made to vmware_puppetfact, I'll
update my fork and submit a new PR.. seem like a reasonable workflow?

**Comment by razorsedge** [comment]
This functionality has been released to the [Forge](https://forge.puppetlabs.com/razorsedge/vmwaretools/4.6.0) in version [4.6.0](https://github.com/razorsedge/puppet-vmwaretools/tree/4.6.0).
